# Generated by Django 4.2 on 2024-06-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estudiante_cedula_alter_profesor_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.profesor'),
        ),
    ]
